/**
 * PRO-228 token pipeline.
 *
 * 1. Computes the Utopia fluid type/space scales (utopia-core) from
 *    tokens/utopia.config.json and writes them as DTCG token files
 *    (tokens/type.tokens.json, tokens/space.tokens.json) so the tokens/
 *    directory always contains the complete DTCG source.
 * 2. Runs Style Dictionary over tokens/*.tokens.json and emits
 *    app/assets/css/tokens.css: a Tailwind v4 `@theme` block plus a `:root`
 *    block for tokens flagged $extensions["ccm.scope"] = "root"
 *    (Nuxt UI semantics such as --ui-radius).
 *
 * Deterministic by construction: pure math from fixed config, no value
 * transforms (oklch()/clamp() strings pass through untouched), fixed file
 * header (no timestamps). Run: pnpm build:tokens
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import StyleDictionary from 'style-dictionary'
import { calculateSpaceScale, calculateTypeScale } from 'utopia-core'

import utopiaConfig from '../tokens/utopia.config.json' with { type: 'json' }

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const GENERATED_NOTE
  = 'GENERATED by scripts/build-tokens.mjs from tokens/utopia.config.json — do not edit by hand.'

function writeJson(relPath, data) {
  writeFileSync(`${repoRoot}${relPath}`, `${JSON.stringify(data, null, 2)}\n`)
}

// ── 1. Utopia scales → DTCG token files ─────────────────────────────────────

const typeSteps = calculateTypeScale(utopiaConfig.type)
  .slice()
  .sort((a, b) => a.step - b.step)

const textGroup = {
  $description: `${GENERATED_NOTE} Utopia fluid type steps for macro rhythm (--text-step-*); Tailwind's static text-sm/base/lg scale stays available for intra-component sizing.`,
}
for (const step of typeSteps) {
  textGroup[`step-${step.label}`] = {
    $value: step.clamp,
    $type: 'dimension',
    $description: `${step.minFontSize}px @ ${utopiaConfig.type.minWidth}px → ${step.maxFontSize}px @ ${utopiaConfig.type.maxWidth}px`,
  }
}
writeJson('tokens/type.tokens.json', { text: textGroup })

const spaceScale = calculateSpaceScale(utopiaConfig.space)

const spacingGroup = {
  $description: `${GENERATED_NOTE} Utopia fluid space scale (--spacing-3xs…3xl + one-up pairs) for macro rhythm; Tailwind's numeric spacing scale stays available for intra-component spacing.`,
}
for (const size of [...spaceScale.sizes, ...spaceScale.oneUpPairs]) {
  spacingGroup[size.label] = {
    $value: size.clamp,
    $type: 'dimension',
    $description: `${size.minSize}px @ ${utopiaConfig.space.minWidth}px → ${size.maxSize}px @ ${utopiaConfig.space.maxWidth}px`,
  }
}
writeJson('tokens/space.tokens.json', { spacing: spacingGroup })

// ── 2. Style Dictionary → @theme CSS ─────────────────────────────────────────

const FILE_HEADER = `/*
 * Generated by scripts/build-tokens.mjs — DO NOT EDIT.
 * Source of truth: tokens/*.tokens.json (DTCG). Rebuild: pnpm build:tokens
 */
`

/** Emit `{radius.sm}` DTCG references as `var(--radius-sm)`. */
function cssValue(token) {
  const original = token.original.$value ?? token.original.value
  if (typeof original === 'string' && /\{[^}]+\}/.test(original)) {
    return original.replace(/\{([^}]+)\}/g, (_, ref) => `var(--${ref.split('.').join('-')})`)
  }
  return token.$value ?? token.value
}

StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const themeLines = []
    const rootLines = []
    for (const token of dictionary.allTokens) {
      const line = `  --${token.path.join('-')}: ${cssValue(token)};`
      if (token.$extensions?.['ccm.scope'] === 'root') {
        rootLines.push(line)
      }
      else {
        themeLines.push(line)
      }
    }
    // `static` so every token variable is always emitted: consumers (and the
    // playground docs page) reference tokens dynamically via var(--...), which
    // Tailwind's usage scanner cannot see — without `static` those variables
    // would be tree-shaken out of the built CSS.
    return `${FILE_HEADER}
@theme static {
${themeLines.join('\n')}
}

:root {
${rootLines.join('\n')}
}
`
  },
})

const sd = new StyleDictionary({
  source: [`${repoRoot}tokens/*.tokens.json`],
  log: { verbosity: 'silent' },
  platforms: {
    css: {
      transforms: [],
      buildPath: `${repoRoot}app/assets/css/`,
      files: [{ destination: 'tokens.css', format: 'css/tailwind-theme' }],
    },
  },
})

await sd.buildAllPlatforms()

process.stdout.write(
  'tokens: wrote tokens/type.tokens.json, tokens/space.tokens.json, app/assets/css/tokens.css\n',
)
